
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Fallback for DATABASE_URL if it's not set, but ONLY in non-production environments.
// This prevents Prisma from masking configuration errors on Heroku behind connection failures to localhost.
if (!process.env.DATABASE_URL) {
  const isHeroku = !!process.env.DYNO;
  const isProduction = process.env.NODE_ENV === "production";

  if (!isHeroku && !isProduction) {
    process.env.DATABASE_URL = "postgresql://postgres:Bhuvan@123@localhost:5432/bhuvan_app?schema=public";
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || "",
  },
});
