
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Force a fallback for DATABASE_URL if it's not set. 
// This prevents Prisma from crashing during the build phase on Heroku.
if (!process.env.DATABASE_URL) {
  process.env.DATABASE_URL = "postgresql://postgres:Bhuvan@123@localhost:5432/bhuvan_app?schema=public";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
